# Generated by Django 5.0.6 on 2024-08-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='image',
            field=models.ImageField(default='halls/default.jpg', upload_to='halls/'),
        ),
    ]
